### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by jellopudding** [TheNOOFClan/S.C.S.I.#10]
links, installation, maintenance, etc.

**Comment by jellopudding** [comment]
We can probably steal from the wiki

**Comment by astapa** [comment]
We have a wiki?

**Comment by jellopudding** [comment]
https://github.com/TheNOOFClan/S.C.S.I./wiki

**Comment by jellopudding** [comment]
eabfa00bcfab994c29bd99b3dd8208cbd8499962
